# Single source of truth for UI strings (pt-PT default + English).
# Regenerate with: python3 tools/strings_source.py   (writes values/ and values-en/strings.xml)
S = [
("app_name", "DECO PROteste Sócio (demo)", "DECO PROteste Member (demo)"),
("action_back", "Voltar", "Back"),
("action_enable", "Ativar", "Turn on"),
("action_finish_and_logout", "Concluir e terminar sessão", "Finish and sign out"),
("action_login", "Entrar", "Sign in"),
("action_logout", "Terminar sessão", "Sign out"),
("action_ok", "OK", "OK"),
("action_privacy_policy", "Política de privacidade", "Privacy policy"),
("action_read", "Ler artigo", "Read article"),
("action_refresh", "Atualizar", "Refresh"),
("action_retry", "Tentar novamente", "Try again"),
("action_save", "Guardar", "Save"),
("tab_news", "Notícias", "News"),
("tab_membership", "Assinatura", "Subscription"),
("tab_rewards", "Recompensas", "Rewards"),
("tab_profile", "Perfil", "Profile"),
("brand_logo_description", "Logótipo", "Logo"),
("login_title", "Área de Sócio", "Member area"),
("login_subtitle", "Entre com a mesma conta que usa no site.", "Sign in with the same account you use on the website."),
("login_use_demo_account", "Usar conta de demonstração", "Use demo account"),
("login_demo_hint", "Demonstração: demo@exemplo.pt · demo1234", "Demo: demo@exemplo.pt · demo1234"),
("login_error_credentials", "Email ou palavra-passe incorretos.", "Incorrect email or password."),
("login_error_empty", "Introduza o email e a palavra-passe.", "Enter your email and password."),
("field_email", "Email", "Email"),
("field_password", "Palavra-passe", "Password"),
("field_first_name", "Nome", "First name"),
("field_last_name", "Apelido", "Last name"),
("field_phone", "Telemóvel", "Mobile phone"),
("field_street", "Morada", "Street address"),
("field_postal_code", "Código postal", "Postal code"),
("field_city", "Localidade", "City"),
("field_error_required", "Campo obrigatório.", "Required field."),
("field_error_email", "Introduza um email válido.", "Enter a valid email."),
("field_error_phone", "Introduza um número de telefone válido.", "Enter a valid phone number."),
("field_error_postal_code", "Use o formato 0000-000.", "Use the format 0000-000."),
("onboarding_title", "Privacidade", "Privacy"),
("onboarding_intro", "Antes de começar, decida como podemos comunicar consigo. Nada está pré-selecionado.", "Before you start, decide how we may contact you. Nothing is preselected."),
("onboarding_notifications_title", "Notificações", "Notifications"),
("onboarding_notifications_body", "Usamos notificações para avisos da sua conta, como a renovação da assinatura. As promocionais só são enviadas se as aceitar abaixo.", "We use notifications for account notices such as subscription renewal. Promotional ones are only sent if you accept them below."),
("onboarding_notifications_allow", "Permitir notificações", "Allow notifications"),
("onboarding_notifications_granted", "Notificações permitidas", "Notifications allowed"),
("onboarding_marketing_heading", "Comunicações de marketing", "Marketing communications"),
("onboarding_withdraw_note", "Pode retirar o consentimento a qualquer momento em Perfil › Consentimentos, sem afetar a sua assinatura.", "You can withdraw consent at any time in Profile › Consents without affecting your subscription."),
("onboarding_save", "Guardar escolhas e continuar", "Save choices and continue"),
("onboarding_reject_all", "Recusar todas e continuar", "Decline all and continue"),
("consent_newsletter_title", "Newsletter por email", "Email newsletter"),
("consent_newsletter_description", "Receber a newsletter com artigos, testes e alertas de consumo.", "Receive the newsletter with articles, tests and consumer alerts."),
("consent_push_title", "Notificações promocionais", "Promotional notifications"),
("consent_push_description", "Receber nesta app notificações sobre campanhas, descontos e novidades.", "Receive notifications in this app about campaigns, discounts and news."),
("consent_partners_title", "Ofertas de parceiros", "Partner offers"),
("consent_partners_description", "Receber ofertas de parceiros selecionados. Os seus dados não são vendidos.", "Receive offers from selected partners. Your data is not sold."),
("consent_personalisation_title", "Conteúdo personalizado", "Personalised content"),
("consent_personalisation_description", "Usar a forma como utiliza a app para recomendar artigos e ofertas.", "Use how you use the app to recommend articles and offers."),
("consents_title", "Consentimentos", "Consents"),
("consents_intro", "Escolha como quer que o contactemos. Pode alterar estas opções a qualquer momento; cada alteração fica registada.", "Choose how we may contact you. You can change these options at any time; every change is recorded."),
("consents_saved", "Preferências guardadas.", "Preferences saved."),
("consents_history_title", "Histórico de consentimentos", "Consent history"),
("consents_history_empty", "Ainda não há registos.", "No records yet."),
("consents_history_granted", "Aceite em %1$s · texto %2$s", "Granted on %1$s · text %2$s"),
("consents_history_revoked", "Recusado em %1$s · texto %2$s", "Declined on %1$s · text %2$s"),
("news_title", "Notícias", "News"),
("news_article_title", "Artigo", "Article"),
("news_empty", "Sem artigos de momento.", "No articles right now."),
("news_sample_banner", "Versão de demonstração: artigos de exemplo.", "Demo version: sample articles."),
("news_fallback_banner", "Não foi possível carregar as notícias. A mostrar artigos de exemplo.", "Couldn't load the news. Showing sample articles."),
("news_sample_label", "Exemplo", "Sample"),
("news_members_only", "Exclusivo sócios", "Members only"),
("news_open_website", "Abrir no site", "Open on website"),
("membership_title", "Assinatura", "Subscription"),
("status_active", "Ativa", "Active"),
("status_expiring", "A expirar", "Expiring"),
("status_expired", "Expirada", "Expired"),
("per_month", "por mês", "per month"),
("per_quarter", "por trimestre", "per quarter"),
("per_year", "por ano", "per year"),
("membership_renews_on", "Renova automaticamente em %1$s", "Renews automatically on %1$s"),
("membership_valid_until", "Válida até %1$s", "Valid until %1$s"),
("membership_expires_on", "Expira em %1$s", "Expires on %1$s"),
("membership_expired_on", "Expirou em %1$s", "Expired on %1$s"),
("membership_auto_renew_on", "Renovação automática ativada", "Auto-renewal on"),
("membership_auto_renew_off", "Renovação automática desativada", "Auto-renewal off"),
("membership_payment_method", "Pagamento: %1$s", "Payment: %1$s"),
("membership_renew", "Renovar assinatura", "Renew subscription"),
("membership_renew_note", "A renovação é feita no site, numa página de pagamento segura.", "Renewal is completed on the website, on a secure payment page."),
("membership_expired_banner", "A sua assinatura expirou. Os benefícios de sócio ficam suspensos até renovar.", "Your subscription has expired. Member benefits are paused until you renew."),
("addons_title", "Serviços adicionais", "Add-on services"),
("addons_intro", "Serviços adicionais à sua assinatura. Pode ativá-los e desativá-los aqui.", "Extra services on top of your subscription. You can turn them on and off here."),
("addon_kind_digital", "Conteúdo digital", "Digital content"),
("addon_kind_service", "Serviço", "Service"),
("addon_kind_insurance", "Seguro", "Insurance"),
("addon_kind_advice", "Aconselhamento", "Advice"),
("addon_state_active", "Ativo", "Active"),
("addon_state_ending", "A terminar", "Ending"),
("addon_activate", "Ativar", "Activate"),
("addon_withdraw", "Retrate-se do contrato aqui", "Withdraw from the contract here"),
("addon_cancel", "Cancelar serviço", "Cancel service"),
("addon_undo_cancel", "Anular cancelamento", "Undo cancellation"),
("addon_active_since", "Ativo desde %1$s.", "Active since %1$s."),
("addon_active_since_withdraw", "Ativo desde %1$s. Pode desistir sem custos até %2$s.", "Active since %1$s. You can withdraw free of charge until %2$s."),
("addon_ends_on", "Termina em %1$s.", "Ends on %1$s."),
("addon_digital_billing_note", "Conteúdo digital: na versão publicada, a compra é feita através do Google Play.", "Digital content: in the published app, this is bought through Google Play."),
("addon_activated", "%1$s ativado.", "%1$s activated."),
("addon_cancelled", "Cancelamento de %1$s registado.", "Cancellation of %1$s recorded."),
("addon_kept", "%1$s continua ativo.", "%1$s stays active."),
("addon_confirm_activate_title", "Ativar %1$s?", "Activate %1$s?"),
("addon_confirm_activate_body", "Preço: %1$s. Ao confirmar, celebra um contrato com obrigação de pagamento. Tem %2$d dias para desistir sem custos.", "Price: %1$s. By confirming you enter a contract with an obligation to pay. You have %2$d days to withdraw free of charge."),
("addon_confirm_activate_button", "Ativar com obrigação de pagar", "Activate with obligation to pay"),
("addon_confirm_withdraw_title", "Retratar-se do contrato?", "Withdraw from the contract?"),
("addon_confirm_withdraw_body", "Vai retratar-se do contrato de %1$s dentro do prazo legal de 14 dias. O serviço termina de imediato e será reembolsado em %2$s.", "You are withdrawing from the %1$s contract within the 14-day legal period. The service ends immediately and you will be refunded %2$s."),
("addon_confirm_withdraw_button", "Confirmar retratação", "Confirm withdrawal"),
("addon_confirm_cancel_title", "Cancelar %1$s?", "Cancel %1$s?"),
("addon_confirm_cancel_body", "O serviço mantém-se ativo até ao fim do período já pago e depois termina. Pode anular o cancelamento até lá.", "The service stays active until the end of the period already paid, then ends. You can undo the cancellation until then."),
("addon_confirm_cancel_button", "Cancelar serviço", "Cancel service"),
("addon_confirm_undo_title", "Manter %1$s?", "Keep %1$s?"),
("addon_confirm_undo_body", "O serviço continua ativo e será renovado normalmente.", "The service stays active and renews as usual."),
("addon_confirm_undo_button", "Manter serviço", "Keep service"),
("withdrawal_receipt_title", "Retratação registada", "Withdrawal recorded"),
("withdrawal_receipt_service", "Serviço: %1$s", "Service: %1$s"),
("withdrawal_receipt_date", "Data: %1$s", "Date: %1$s"),
("withdrawal_receipt_refund", "Reembolso: %1$s", "Refund: %1$s"),
("withdrawal_receipt_reference", "Referência: %1$s", "Reference: %1$s"),
("withdrawal_receipt_email", "Enviaremos esta confirmação para o seu email.", "We will send this confirmation to your email."),
("rewards_title", "Recompensas", "Rewards"),
("rewards_points_label", "Os seus pontos", "Your points"),
("rewards_points_value", "%1$d pontos", "%1$d points"),
("rewards_tier", "Nível %1$s", "%1$s tier"),
("rewards_next_tier", "Faltam %1$d pontos para o nível %2$s.", "%1$d points to reach %2$s."),
("tier_bronze", "Bronze", "Bronze"),
("tier_silver", "Prata", "Silver"),
("tier_gold", "Ouro", "Gold"),
("rewards_tab_rewards", "Recompensas", "Rewards"),
("rewards_tab_campaigns", "Campanhas", "Campaigns"),
("rewards_tab_coupons", "Os meus cupões", "My coupons"),
("rewards_empty", "Sem recompensas disponíveis.", "No rewards available."),
("campaigns_empty", "De momento não há campanhas disponíveis.", "No campaigns available right now."),
("coupons_empty", "Ainda não tem cupões.", "You have no coupons yet."),
("reward_redeem", "Trocar", "Redeem"),
("reward_redeem_for", "Trocar por %1$d pontos", "Redeem for %1$d points"),
("reward_missing_points", "Faltam %1$d pontos.", "%1$d more points needed."),
("reward_confirm_title", "Trocar por %1$s?", "Redeem %1$s?"),
("reward_confirm_body", "Vai usar %1$d pontos. O cupão fica válido durante %2$d dias.", "You will use %1$d points. The coupon is valid for %2$d days."),
("campaign_valid_until", "Válido até %1$s", "Valid until %1$s"),
("campaign_claim", "Obter código", "Get code"),
("campaign_show_code", "Ver o meu código", "Show my code"),
("campaign_sold_out", "Esgotado", "Sold out"),
("campaign_codes_left", "Códigos restantes: %1$d", "Codes left: %1$d"),
("coupon_title", "Cupão", "Coupon"),
("coupon_open", "Abrir cupão", "Open coupon"),
("coupon_status_active", "Válido", "Valid"),
("coupon_status_used", "Utilizado", "Used"),
("coupon_status_expired", "Expirado", "Expired"),
("coupon_qr_description", "Código QR do cupão", "Coupon QR code"),
("coupon_copy", "Copiar código", "Copy code"),
("coupon_copied", "Código copiado.", "Code copied."),
("coupon_single_use_note", "Código de utilização única. Apresente-o na loja ou introduza-o na compra online.", "Single-use code. Show it in store or enter it when buying online."),
("profile_title", "Perfil", "Profile"),
("profile_member_number", "Sócio n.º %1$s", "Member no. %1$s"),
("profile_edit", "Editar dados pessoais", "Edit personal details"),
("profile_edit_note", "As alterações são sincronizadas com a sua conta DECO PROteste.", "Changes are synced with your DECO PROteste account."),
("profile_address_section", "Morada", "Address"),
("profile_notifications_section", "Notificações", "Notifications"),
("profile_notifications_system", "Notificações da app", "App notifications"),
("profile_notifications_on", "Ativadas", "On"),
("profile_notifications_off", "Desativadas", "Off"),
("profile_service_notifications", "Avisos da minha conta", "Account notices"),
("profile_service_notifications_description", "Renovação, serviços adicionais e segurança. Não inclui publicidade.", "Renewal, add-on services and security. No advertising."),
("profile_privacy_section", "Privacidade", "Privacy"),
("profile_app_section", "Aplicação", "App"),
("profile_language", "Idioma", "Language"),
("profile_version", "Versão %1$s · modo %2$s", "Version %1$s · %2$s mode"),
("language_system", "Idioma do sistema", "System language"),
("language_portuguese", "Português (Portugal)", "Português (Portugal)"),
("language_english", "English", "English"),
("my_data_title", "Os meus dados", "My data"),
("my_data_intro", "Pode consultar e descarregar uma cópia dos seus dados num formato legível por máquina.", "You can view and download a copy of your data in a machine-readable format."),
("my_data_categories_title", "Que dados temos", "What data we hold"),
("my_data_categories", "• Identificação e contactos\\n• Assinatura e serviços adicionais\\n• Consentimentos e respetivo histórico\\n• Pontos, recompensas e cupões", "• Identity and contact details\\n• Subscription and add-on services\\n• Consents and their history\\n• Points, rewards and coupons"),
("my_data_export", "Exportar (JSON)", "Export (JSON)"),
("my_data_preview_title", "Pré-visualização", "Preview"),
("my_data_saved", "Ficheiro guardado.", "File saved."),
("my_data_save_failed", "Não foi possível guardar o ficheiro.", "The file could not be saved."),
("delete_title", "Eliminar conta", "Delete account"),
("delete_intro", "Pode pedir a eliminação da sua conta da app e dos dados pessoais associados.", "You can ask us to delete your app account and the personal data linked to it."),
("delete_what_is_deleted", "Eliminamos: perfil, preferências, consentimentos de marketing, pontos e cupões.", "We delete: profile, preferences, marketing consents, points and coupons."),
("delete_what_is_kept", "Mantemos apenas o que a lei obriga, como faturas, durante o prazo legal.", "We keep only what the law requires, such as invoices, for the legal period."),
("delete_subscription_note", "Eliminar a conta não cancela automaticamente a assinatura paga. Se quiser terminá-la, cancele-a também.", "Deleting the account does not automatically cancel your paid subscription. If you want to end it, cancel it too."),
("delete_confirm_checkbox", "Compreendo que esta ação não pode ser anulada.", "I understand this cannot be undone."),
("delete_action", "Pedir eliminação da conta", "Request account deletion"),
("delete_done_title", "Pedido recebido", "Request received"),
("delete_done_reference", "Referência do pedido: %1$s", "Request reference: %1$s"),
("delete_done_deadline", "Conclusão prevista até %1$s.", "Expected completion by %1$s."),
("delete_done_email", "Enviaremos a confirmação por email.", "We will send the confirmation by email."),
("demo_title", "Menu de demonstração", "Demo menu"),
("demo_bff_mode_note", "Modo BFF: os cenários abaixo só funcionam no modo demo.", "BFF mode: the scenarios below only work in demo mode."),
("demo_subscription_section", "Estado da assinatura", "Subscription state"),
("demo_states_section", "Estados da app", "App states"),
("demo_network_error", "Simular falha de rede", "Simulate network failure"),
("demo_empty_coupons", "Sem cupões nem campanhas", "No coupons or campaigns"),
("demo_reset", "Repor dados de demonstração", "Reset demo data"),
("demo_push_section", "Notificações", "Notifications"),
("demo_test_push", "Enviar notificação de teste", "Send test notification"),
("demo_test_push_title", "Aviso da assinatura", "Subscription notice"),
("demo_test_push_body", "A sua assinatura renova daqui a 12 dias. Toque para ver os detalhes.", "Your subscription renews in 12 days. Tap to see the details."),
("demo_test_push_sent", "Notificação enviada.", "Notification sent."),
("demo_test_push_blocked", "As notificações estão desativadas para esta app.", "Notifications are turned off for this app."),
("channel_service_name", "Avisos da minha conta", "Account notices"),
("channel_service_description", "Renovação da assinatura, serviços e alertas da sua conta.", "Subscription renewal, services and account alerts."),
("channel_marketing_name", "Novidades e ofertas", "News and offers"),
("channel_marketing_description", "Novidades, ofertas e campanhas (só com o seu consentimento).", "News, offers and campaigns (only with your consent)."),
("error_generic", "Algo correu mal. Tente novamente.", "Something went wrong. Please try again."),
("error_network", "Sem ligação. Verifique a internet e tente novamente.", "No connection. Check your internet and try again."),
("error_unauthorized", "A sessão terminou. Entre novamente.", "Your session has ended. Please sign in again."),
("error_validation", "Verifique os campos assinalados.", "Please check the highlighted fields."),
("error_not_found", "Não encontrado.", "Not found."),
("error_subscription_expired", "Esta opção requer uma assinatura ativa. Renove para continuar.", "This needs an active subscription. Renew to continue."),
("error_already_active", "Este serviço já está ativo.", "This service is already active."),
("error_not_active", "Este serviço não está ativo.", "This service is not active."),
("error_withdrawal_over", "O prazo de 14 dias para desistir terminou. Pode cancelar o serviço.", "The 14-day withdrawal period has ended. You can cancel the service instead."),
("error_insufficient_points", "Não tem pontos suficientes.", "You don't have enough points."),
("error_coupon_expired", "Esta campanha já terminou.", "This campaign has ended."),
("error_coupon_pool_empty", "Os códigos desta campanha esgotaram.", "This campaign has run out of codes."),
("error_deletion_already_requested", "Já existe um pedido de eliminação em curso.", "A deletion request is already in progress."),
]

PLURALS = [
    ("days_left",
     {"one": "falta %1$d dia", "many": "faltam %1$d dias", "other": "faltam %1$d dias"},
     {"one": "%1$d day left", "other": "%1$d days left"}),
]

def esc(text):
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = text.replace("'", "\\'").replace('"', '\\"')
    return text

def render(index):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated from tools/strings_source.py. Edit that file, not this one. -->',
           '<resources>']
    for key, *vals in S:
        out.append(f'    <string name="{key}">{esc(vals[index])}</string>')
    for key, pt, en in PLURALS:
        forms = (pt, en)[index]
        out.append(f'    <plurals name="{key}">')
        for q, v in forms.items():
            out.append(f'        <item quantity="{q}">{esc(v)}</item>')
        out.append('    </plurals>')
    out.append('</resources>')
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    import os
    base = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
    keys = [k for k, *_ in S]
    assert len(keys) == len(set(keys)), "duplicate keys"
    for folder, index in (("values", 0), ("values-en", 1)):
        with open(os.path.join(base, folder, "strings.xml"), "w", encoding="utf-8") as f:
            f.write(render(index))
    print(f"{len(S)} strings, {len(PLURALS)} plurals")
